#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o verbose


# check java version

# build rice from proper branch
#/path/to/rice$ JAVA_OPTS="-Xmx2g -XX:MaxPermSize=512m -XX:+UseConcMarkSweepGC" mvn clean install 

# build coeus-api

# build coeus-s2sgen

# make sure oracle driver is in .m2 repo (ron added oracle dependency to kc pom.xml)

# copy kc-config.xml to ~kuali/main/dev60 and modify where needed

# make sure VPN or ssh tunnel is set up for db access

# build kc
MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512m -XX:+UseConcMarkSweepGC" mvn -DskipTests -Dmaven.test.skip=true clean install 

# if you just want to build impl and webapp projects, add this:
#  -pl coeus-impl,coeus-webapp

# start coeus-webapp via jetty server
./start


