#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -o verbose

cd coeus-webapp 

MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512m -Doracle.jdbc.Trace=true -javaagent:/home/jlolofie/.m2/repository/org/springframework/spring-instrument/3.2.12.RELEASE/spring-instrument-3.2.12.RELEASE.jar" mvn jetty:run


