git checkout uh-modifications-initial-effort-6.0.1 ../../Upgrade6.0.xlsx
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-data-conv/README.md
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-data-conv/runDataConv.sh
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-data-conv/src/main/java/org/kuali/coeus/dc/Main.java
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-data-conv/src/main/java/org/kuali/coeus/dc/access/kim/RoleDaoImpl.java
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-data-conv/src/main/java/org/kuali/coeus/dc/access/proposal/ProposalKimAttributeDocumentValueHandler.java
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-xml/src/main/resources/org/kuali/coeus/coeus-xml/2/AwardBudgetDocument.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-db/coeus-db-xml/src/main/resources/org/kuali/coeus/coeus-xml/2/TimeAndMoneyDocument.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-impl/pom.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-impl/src/main/resources/KcBootstrapSpringBeans.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-impl/src/main/resources/org/kuali/kra/datadictionary/krad/common/KcApplicationHeader.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-it/pom.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-webapp/pom.xml
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-webapp/src/main/resources/log4j.properties
git checkout uh-modifications-initial-effort-6.0.1 ../../coeus-webapp/src/main/webapp/uh_processUHIMS.jsp
git checkout uh-modifications-initial-effort-6.0.1 ../../pom.xml
